// <auto-generated />
using Eleva_WebAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Eleva_WebAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210618035113_new3")]
    partial class new3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("Eleva_WebAPI.Models.Escola", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("cidade")
                        .HasColumnType("TEXT");

                    b.Property<string>("endereco")
                        .HasColumnType("TEXT");

                    b.Property<string>("estado")
                        .HasColumnType("TEXT");

                    b.Property<string>("nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("telefone")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Escolas");

                    b.HasData(
                        new
                        {
                            id = 1,
                            cidade = "Belo Horizonte",
                            endereco = "R. dos Agrônomos, 185",
                            estado = "MG",
                            nome = "Coleguium - Alípio de Melo",
                            telefone = "(31) 3024-9540"
                        },
                        new
                        {
                            id = 2,
                            cidade = "Belo Horizonte",
                            endereco = "Av. Celso Porfírio Machado, 1650",
                            estado = "MG",
                            nome = "Coleguium - Belvedere Internacional",
                            telefone = "(31) 3568-3807"
                        });
                });

            modelBuilder.Entity("Eleva_WebAPI.Models.Turma", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EscolaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("codigo")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("EscolaId");

                    b.ToTable("Turmas");

                    b.HasData(
                        new
                        {
                            id = 1,
                            EscolaId = 1,
                            codigo = "1A-1"
                        },
                        new
                        {
                            id = 2,
                            EscolaId = 1,
                            codigo = "1A-2"
                        },
                        new
                        {
                            id = 3,
                            EscolaId = 1,
                            codigo = "1A-3"
                        },
                        new
                        {
                            id = 4,
                            EscolaId = 1,
                            codigo = "1B-1"
                        },
                        new
                        {
                            id = 5,
                            EscolaId = 1,
                            codigo = "1B-2"
                        },
                        new
                        {
                            id = 6,
                            EscolaId = 2,
                            codigo = "1A-1"
                        },
                        new
                        {
                            id = 7,
                            EscolaId = 2,
                            codigo = "1A-2"
                        },
                        new
                        {
                            id = 8,
                            EscolaId = 2,
                            codigo = "1A-3"
                        },
                        new
                        {
                            id = 9,
                            EscolaId = 2,
                            codigo = "1B-1"
                        },
                        new
                        {
                            id = 10,
                            EscolaId = 2,
                            codigo = "1B-2"
                        });
                });

            modelBuilder.Entity("Eleva_WebAPI.Models.Turma", b =>
                {
                    b.HasOne("Eleva_WebAPI.Models.Escola", "Escola")
                        .WithMany()
                        .HasForeignKey("EscolaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Escola");
                });
#pragma warning restore 612, 618
        }
    }
}
